spring:
  application:
    name: app
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:java-project-99-secret-key-for-jwt-token-very-long-string}
  expiration: ${JWT_EXPIRATION:86400}
